/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness. Deliberately checks nothing.
         *
         *     "Is this process able to serve a request" -- and nothing else. A liveness
         *     probe that touches the database restarts every instance when the database
         *     blinks, which is how a recoverable outage becomes a crash loop. Use
         *     /readyz to decide whether to send traffic here.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus exposition.
         *
         *     Behind the admin key rather than open: it is a precise description of your
         *     traffic and failure rates. Most scrapers can send a header.
         *
         *     Per-process and in memory, so under several workers a scrape sees one of
         *     them. `prometheus_client`'s multiprocess mode is the answer when that
         *     matters; until then, one worker keeps these honest.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness. Checks the dependencies, and says which one is unhappy.
         *
         *     503 when Postgres is unreachable; 200 with status "degraded" when only
         *     Redis is, because the read path survives that and a shared cache failure
         *     must not empty the load balancer. See app/health.py.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Grant
         * @description Comp a user to a tier without inventing a fake subscription.
         *
         *     Resolution takes the higher of grant and subscription, so this lifts a free
         *     user up and never silently downgrades a paying one.
         */
        post: operations["create_grant_v1_admin_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/grants/{grant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Grant */
        delete: operations["revoke_grant_v1_admin_grants__grant_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sales-inquiries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sales Inquiries List
         * @description The Enterprise lead queue, newest first.
         *
         *     Behind the admin key with everything else here: these are names, email
         *     addresses and stated seat counts of people evaluating the product, which is
         *     commercially sensitive and personal data besides.
         *
         *     `handled=false` is the working view -- what nobody has replied to yet.
         */
        get: operations["sales_inquiries_list_v1_admin_sales_inquiries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sales-inquiries/{inquiry_id}/handled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Inquiry Handled
         * @description Mark a lead as followed up, so the queue means something.
         */
        post: operations["mark_inquiry_handled_v1_admin_sales_inquiries__inquiry_id__handled_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect User
         * @description Everything support needs on one screen: what they are entitled to, what
         *     Stripe objects sit behind it, and every transition that got them here.
         */
        get: operations["inspect_user_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/extend-grace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend Grace
         * @description Push a past_due customer's cut-off back while they sort out a card.
         */
        post: operations["extend_grace_v1_admin_users__user_id__extend_grace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}/resync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resync
         * @description Force a re-read from Stripe. The fix for a webhook we missed.
         */
        post: operations["resync_v1_admin_users__user_id__resync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Cancel at the end of the paid period.
         *
         *     In the app rather than only in Stripe's portal: cancelling is the one thing
         *     a customer should never have to hunt for, and a support ticket asking how
         *     to leave costs more than the button.
         *
         *     Immediate cancellation is deliberately not offered here. They paid through
         *     the period, so ending it early is a refund conversation -- which is what the
         *     portal and Stripe's dashboard are for.
         */
        post: operations["cancel_v1_billing_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Start a hosted checkout. Grants nothing -- the webhook does that.
         */
        post: operations["checkout_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/contact-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contact Sales
         * @description Record an Enterprise inquiry.
         *
         *     Deliberately public. The pricing page is unauthenticated, and the leads
         *     worth having are often from people evaluating before they sign up --
         *     requiring a login here would filter out exactly those.
         *
         *     That makes this the only unauthenticated write in the service, so it is
         *     rate limited per caller (app/ratelimit.py) as well as length-bounded by
         *     ContactSalesRequest. The limiter runs as a dependency, before the body is
         *     validated, so malformed attempts are counted too. It fails open, so
         *     `rate_limit_errors_total` is the metric that says it has stopped limiting;
         *     `sales_inquiries_total` remains the signal for a flood that gets through.
         *
         *     Nothing is emailed from here. Recording it durably is the job; who gets
         *     notified is a workflow decision, and a background send would be one more
         *     thing to fail inside a request the customer is waiting on.
         */
        post: operations["contact_sales_v1_billing_contact_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Billing Health
         * @description Cheap config check: are the prices this service needs actually set?
         */
        get: operations["billing_health_v1_billing_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plans
         * @description The catalog, for the pricing page.
         *
         *     Limits come from plans.py; amounts come from Stripe, which owns what a price
         *     costs. Neither is duplicated in the frontend -- a pricing page that
         *     hard-codes "$20/mo" is a pricing page that will eventually lie.
         *
         *     Cached, because this is public and unauthenticated, and because it should
         *     not put a Stripe API call in front of every visitor.
         */
        get: operations["plans_v1_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Portal
         * @description Change plan, cancel, update card, download invoices.
         *
         *     All of it is Stripe's hosted portal, which is why this service has no
         *     billing UI of its own and no proration code.
         *
         *     With a `tier`, the session is deep-linked to a confirmation for that plan:
         *     a button that says "Upgrade to Pro" should land on Pro, not on a list the
         *     customer has to search. Which plans the portal will switch between is its
         *     *configuration* -- see scripts/configure_portal.py, without which it offers
         *     only the plan they already have.
         */
        post: operations["portal_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume
         * @description Undo a pending cancellation.
         *
         *     Paired with /cancel deliberately. An app that makes leaving easy and coming
         *     back hard has only moved the friction somewhere less honest, and "reactivate
         *     in the portal" is not a call to action anyone can follow.
         */
        post: operations["resume_v1_billing_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Subscription */
        get: operations["my_subscription_v1_billing_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Entitlements
         * @description What this user may do right now.
         *
         *     The one call the product makes. Clients should branch on quotas and features
         *     here, never on the tier name -- that way changing a limit is a config edit,
         *     not a frontend release.
         */
        get: operations["my_entitlements_v1_entitlements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Events
         * @description Webhook health at a glance: what arrived, what failed, how far behind.
         *
         *     Guarded explicitly, because this router is otherwise unauthenticated by
         *     necessity -- Stripe cannot send an admin key, so `/stripe` is protected by
         *     signature verification instead. Anything else added here needs its own
         *     dependency, and this one shipped without it: the rows include `error`, which
         *     holds a truncated traceback, so it was serving stack traces to the internet.
         */
        get: operations["recent_events_v1_webhooks_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe Webhook */
        post: operations["stripe_webhook_v1_webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BillingInterval
         * @enum {string}
         */
        BillingInterval: "monthly" | "annual";
        /** ChatQuota */
        ChatQuota: {
            /** Key */
            key: string;
            /** Limit */
            limit: number | null;
            /** Remaining */
            remaining: number | null;
            /** Used */
            used: number;
        };
        /** ChatReply */
        ChatReply: {
            /** Model */
            model: string;
            quota: components["schemas"]["ChatQuota"];
            /** Reply */
            reply: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Model
             * @default small
             */
            model: string;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Cancel Url */
            cancel_url?: string | null;
            /** @default monthly */
            interval: components["schemas"]["BillingInterval"];
            /** Promo Code */
            promo_code?: string | null;
            /** Success Url */
            success_url?: string | null;
            tier: components["schemas"]["Tier"];
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Checkout Url */
            checkout_url: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * ContactSalesRequest
         * @description An Enterprise inquiry.
         *
         *     Every field is length-bounded. This endpoint is public by necessity -- the
         *     pricing page is -- so the request body is attacker-controlled, and an
         *     unbounded string here is a way to fill a database for free.
         */
        ContactSalesRequest: {
            /** Company */
            company?: string | null;
            /** Email */
            email: string;
            /** Message */
            message?: string | null;
            /** Seats */
            seats?: number | null;
            /**
             * Source
             * @default pricing_page
             * @enum {string}
             */
            source: "pricing_page" | "paywall" | "billing_page";
        };
        /** ContactSalesResponse */
        ContactSalesResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @default received
             * @constant
             */
            status: "received";
        };
        /**
         * Discount
         * @description A discount mirrored from Stripe; see stripe_client._discount.
         */
        Discount: {
            /** Amount Off */
            amount_off: number | null;
            /** Coupon Id */
            coupon_id: string | null;
            /** Currency */
            currency: string | null;
            /** Duration */
            duration: string | null;
            /** Duration In Months */
            duration_in_months: number | null;
            /**
             * Ends At
             * @description unix seconds; null if it never ends
             */
            ends_at: number | null;
            /** Name */
            name: string | null;
            /** Percent Off */
            percent_off: number | null;
            /** Promotion Code */
            promotion_code: string | null;
        };
        /**
         * EntitlementResponse
         * @description The only shape the product should ever branch on.
         */
        EntitlementResponse: {
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end: string | null;
            /** Display Name */
            display_name: string;
            features: components["schemas"]["Features"];
            /**
             * Grace Ends At
             * @description set while past_due; access ends here
             */
            grace_ends_at: string | null;
            /** Quotas */
            quotas: components["schemas"]["QuotaState"][];
            /**
             * Source
             * @enum {string}
             */
            source: "subscription" | "grant" | "default";
            status: components["schemas"]["SubscriptionStatus"];
            tier: components["schemas"]["Tier"];
            /** User Id */
            user_id: string;
        };
        /**
         * Features
         * @description What a tier includes beyond its counted quotas.
         *
         *     Spelled out rather than `dict[str, Any]` so the pricing page and the
         *     paywall get real types. A feature added to a tier in plans.py has to be
         *     added here too, which tests/test_api_types.py enforces.
         */
        Features: {
            /** Api Access */
            api_access: boolean;
            /**
             * Context Tokens
             * @description null means unlimited
             */
            context_tokens: number | null;
            /**
             * History Retention Days
             * @description null means forever
             */
            history_retention_days: number | null;
            /** Models */
            models: string[];
            /** Support Sla */
            support_sla: string;
        };
        /** GrantRequest */
        GrantRequest: {
            /** Expires At */
            expires_at?: string | null;
            /** Reason */
            reason: string;
            tier: components["schemas"]["Tier"];
            /** User Id */
            user_id: string;
        };
        /** GrantResponse */
        GrantResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Expires At */
            expires_at: string | null;
            /** Id */
            id: string;
            /** Reason */
            reason: string;
            tier: components["schemas"]["Tier"];
            /** User Id */
            user_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanPrice */
        PlanPrice: {
            /** Currency */
            currency: string | null;
            /** Price Id */
            price_id: string;
            /**
             * Unit Amount
             * @description in the currency's smallest unit; null if Stripe was unreachable
             */
            unit_amount: number | null;
        };
        /**
         * PlanResponse
         * @description One card on the pricing page: limits from plans.py, amounts from Stripe.
         */
        PlanResponse: {
            /** Display Name */
            display_name: string;
            features: components["schemas"]["Features"];
            /** Prices */
            prices: {
                [key: string]: components["schemas"]["PlanPrice"];
            };
            /** Purchasable */
            purchasable: boolean;
            /** Quotas */
            quotas: components["schemas"]["QuotaLimit"][];
            /**
             * Sales Led
             * @description sold by a conversation: "Custom" and Contact sales
             */
            sales_led: boolean;
            tier: components["schemas"]["Tier"];
        };
        /**
         * PortalRequest
         * @description Optional: which plan the customer asked for.
         *
         *     The portal opens on its home page without this, which is fine for "Manage
         *     billing" and wrong for a button that named a tier.
         */
        PortalRequest: {
            /** @default monthly */
            interval: components["schemas"]["BillingInterval"];
            tier?: components["schemas"]["Tier"] | null;
        };
        /** PortalResponse */
        PortalResponse: {
            /** Portal Url */
            portal_url: string;
        };
        /**
         * QuotaLimit
         * @description A tier's cap on one counter. The usage against it is QuotaState.
         */
        QuotaLimit: {
            /** Key */
            key: string;
            /**
             * Limit
             * @description null means unlimited
             */
            limit: number | null;
            window: components["schemas"]["QuotaWindow"];
        };
        /** QuotaState */
        QuotaState: {
            /** Key */
            key: string;
            /**
             * Limit
             * @description null means unlimited
             */
            limit: number | null;
            /** Remaining */
            remaining: number | null;
            /**
             * Reset At
             * Format: date-time
             */
            reset_at: string;
            /** Used */
            used: number;
        };
        /**
         * QuotaWindow
         * @description How a counter's window is chosen.
         *
         *     DAILY resets at UTC midnight. BILLING_PERIOD resets on the subscriber's own
         *     renewal date -- which is a different day for almost every customer, and the
         *     reason these two are not interchangeable.
         * @enum {string}
         */
        QuotaWindow: "daily" | "billing_period";
        /** SalesInquirySummary */
        SalesInquirySummary: {
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Tier */
            current_tier: string | null;
            /** Email */
            email: string;
            /** Handled At */
            handled_at: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string | null;
            /** Seats */
            seats: number | null;
            /** Source */
            source: string;
            /** User Id */
            user_id: string | null;
        };
        /**
         * SubscriptionStatus
         * @description Internal status. Deliberately *not* Stripe's vocabulary.
         *
         *     Only TRIALING, ACTIVE and PAST_DUE grant paid entitlements -- PAST_DUE keeps
         *     access until the grace window closes, because most failed renewals are
         *     expired cards and cutting a willing payer off converts them to churn.
         * @enum {string}
         */
        SubscriptionStatus: "free" | "trialing" | "active" | "past_due" | "incomplete" | "paused";
        /** SubscriptionSummary */
        SubscriptionSummary: {
            /** Billing Interval */
            billing_interval: string | null;
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            /** Current Period End */
            current_period_end: string | null;
            /** Current Period Start */
            current_period_start: string | null;
            discount: components["schemas"]["Discount"] | null;
            /** Disputed At */
            disputed_at: string | null;
            /** Past Due Since */
            past_due_since: string | null;
            /** Status */
            status: string;
            /** Stripe Customer Id */
            stripe_customer_id: string | null;
            /** Stripe Price Id */
            stripe_price_id: string | null;
            /** Stripe Subscription Id */
            stripe_subscription_id: string | null;
            tier: components["schemas"]["Tier"];
            /** Trial End */
            trial_end: string | null;
            /** User Id */
            user_id: string;
        };
        /**
         * Tier
         * @enum {string}
         */
        Tier: "free" | "plus" | "pro" | "enterprise";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_grant_v1_admin_grants_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Admin-Actor"?: string;
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_grant_v1_admin_grants__grant_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sales_inquiries_list_v1_admin_sales_inquiries_get: {
        parameters: {
            query?: {
                handled?: boolean | null;
                limit?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesInquirySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_inquiry_handled_v1_admin_sales_inquiries__inquiry_id__handled_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                inquiry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesInquirySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_user_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extend_grace_v1_admin_users__user_id__extend_grace_post: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resync_v1_admin_users__user_id__resync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_billing_cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkout_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contact_sales_v1_billing_contact_sales_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactSalesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactSalesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    billing_health_v1_billing_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    plans_v1_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"][];
                };
            };
        };
    };
    portal_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PortalRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_v1_billing_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_subscription_v1_billing_subscription_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatReply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_entitlements_v1_entitlements_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_events_v1_webhooks_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_v1_webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: {
                "stripe-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
