#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: operator alert email through Resend's SMTP relay.
#
# Why: the nightly reconcile job emails a person when a subscription is still
# charging an account that has been deleted. It speaks plain SMTP
# (app/notify.py), so Resend is configured as an SMTP server: host
# smtp.resend.com, username `resend`, and an API key as the password.
#
# Writes to .env only. CI never runs reconcile, so there are no GitHub secrets;
# a deployed environment needs the same seven values set where it runs.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
PY="$REPO_ROOT/.venv/bin/python"
ENV_FILE="$REPO_ROOT/.env"

banner "Alert email through Resend"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A Resend account"
say "Sign up, or sign in if you already have an account. The free plan is"
say "plenty: this sends at most one email a night, and usually none."
open_url "https://resend.com/signup"
note "The address you sign up with matters in the next stage: without a"
note "verified domain, Resend only delivers to that address."
pause "Signed in?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Who the email comes from"
say "Two ways to send:"
step "Your own domain: any recipient, and what production needs. You add two"
step "or three DNS records and wait for Resend to verify them."
step "Resend's test sender (onboarding@resend.dev): works right now, but only"
step "delivers to the address your Resend account is registered with."
say ""
if confirm "Use your own domain? (No = the test sender for now)"; then
  SENDER_MODE=domain
  say ""
  say "Resend recommends a subdomain, so alert mail cannot hurt your main"
  say "domain's reputation, e.g. alerts.yourdomain.com."
  open_url "https://resend.com/domains"
  step "Click 'Add Domain', enter the subdomain, pick the region nearest you."
  step "Open the domain's Records: copy each record (SPF and DKIM as TXT, plus"
  step "MX or CNAME) into your DNS provider exactly as shown."
  warn "On Cloudflare, leave CNAME records 'DNS only' (grey cloud). Proxied"
  warn "records never verify."
  step "Back in Resend, wait for the domain to show 'Verified'. Usually about"
  step "15 minutes; DNS can take up to 72 hours. Re-run this wizard later if so."
  pause "Domain shows Verified?"
  ask ALERT_EMAIL_FROM "Send from which address on that domain? (e.g. billing-alerts@alerts.yourdomain.com):"
  if [[ "$ALERT_EMAIL_FROM" != *@*.* ]]; then
    warn "That is not an email address. Nothing was written."
    exit 1
  fi
else
  SENDER_MODE=test
  ALERT_EMAIL_FROM="onboarding@resend.dev"
  warn "Test sender: only your Resend account's own address will receive mail."
  note "Switch later by re-running this wizard and choosing your own domain."
fi
write_env ALERT_EMAIL_FROM "$ALERT_EMAIL_FROM"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "An API key, used as the SMTP password"
open_url "https://resend.com/api-keys"
step "Click 'Create API Key' and name it subscription-service-alerts."
step "Permission: 'Sending access', not full access. The key can then only"
step "send email, so a leak cannot read or change anything in your account."
if [[ "$SENDER_MODE" == domain ]]; then
  step "Domain: restrict it to the domain you just verified."
fi
step "Copy the key (it starts re_). Resend shows it once."
ask_secret SMTP_PASSWORD "Paste the API key:"
if [[ "$SMTP_PASSWORD" != re_* ]]; then
  warn "Resend keys start re_. Nothing was written; re-run and paste it again."
  exit 1
fi
write_env SMTP_PASSWORD "$SMTP_PASSWORD"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Resend's SMTP server"
say "Fixed values from Resend's SMTP documentation. Port 587 upgrades to TLS"
say "with STARTTLS before the key is sent."
write_env SMTP_HOST "smtp.resend.com"
write_env SMTP_PORT "587"
write_env SMTP_STARTTLS "true"
write_env SMTP_USERNAME "resend"
note "If your network blocks 587, Resend also listens on 2587 (STARTTLS) and"
note "465 or 2465 (TLS from the start). The code handles both kinds."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Who receives the alerts"
say "Whoever decides whether to cancel or refund a subscription that is still"
say "charging a deleted account. Separate several addresses with commas."
if [[ "$SENDER_MODE" == test ]]; then
  warn "With the test sender this must be your Resend account's address."
fi
ask ALERT_EMAIL_TO "Send alerts to:"
if [[ "$ALERT_EMAIL_TO" != *@* ]]; then
  warn "That is not an email address. Nothing was written."
  exit 1
fi
write_env ALERT_EMAIL_TO "$ALERT_EMAIL_TO"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Send a test email"
say "Through the same code the nightly job uses (app/notify.py), with the"
say "values just written to .env."
if "$PY" - <<'PY'
import asyncio
import smtplib
import sys

from app.config import get_settings
from app.notify import email_notifier

notifier = email_notifier()
if notifier is None:
    print("  Not configured: SMTP_HOST, ALERT_EMAIL_FROM or ALERT_EMAIL_TO is empty in .env.")
    sys.exit(1)

body = (
    "This is a test from scripts/setup_email.sh.\n\n"
    "When the nightly reconcile job finds a subscription that Stripe can still\n"
    "charge but whose Supabase account has been deleted, the alert arrives here.\n"
)
try:
    asyncio.run(notifier.send("[subscription-service] test alert", body))
except smtplib.SMTPAuthenticationError:
    print("  Resend rejected the API key. Re-run and paste the key again.")
    sys.exit(1)
except (smtplib.SMTPSenderRefused, smtplib.SMTPRecipientsRefused, smtplib.SMTPDataError) as exc:
    print(f"  Resend refused the message: {exc}")
    print("  Usually an unverified sending domain, or the test sender addressed to")
    print("  someone other than your Resend account's own address.")
    sys.exit(1)
except (TimeoutError, OSError) as exc:
    print(f"  Could not reach {get_settings().smtp_host}:{get_settings().smtp_port} ({exc}).")
    print("  If your network blocks 587, set SMTP_PORT=2587 in .env and re-run.")
    sys.exit(1)
print(f"  Accepted by Resend for: {', '.join(notifier.recipients)}")
PY
then
  step "Check the inbox (and spam) for '[subscription-service] test alert'."
  note "Resend's Emails page shows whether it was delivered or bounced:"
  note "  https://resend.com/emails"
  pause "Arrived?"
else
  warn "The test email was not sent. Fix the cause above and re-run: values"
  warn "already in .env are offered as defaults."
  SKIPPED+=("a test email that Resend accepted")
fi

say ""
warn "Wherever reconcile is deployed, set the same seven values there:"
note "  SMTP_HOST SMTP_PORT SMTP_STARTTLS SMTP_USERNAME SMTP_PASSWORD"
note "  ALERT_EMAIL_FROM ALERT_EMAIL_TO"
finish
