#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: a Stripe sandbox of this application's own.
#
# Why: this service once shared a sandbox with another product. Webhooks are
# delivered per account, the reconciliation job lists every subscription in the
# account, and portal configurations and price namespaces are account-wide. The
# code ignores subscriptions that are not on its own prices, but a sandbox of
# its own removes the whole class of problem. Re-run this to move to a fresh
# sandbox, e.g. after resetting one.
#
# Nothing here deletes anything in Stripe. The old sandbox keeps its data; this
# only points the application at a new one.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
PY="$REPO_ROOT/.venv/bin/python"
ENV_FILE="$REPO_ROOT/.env"

banner "A Stripe sandbox for subscription-service"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the sandbox"
say "One sandbox for this application alone, shared with no other product."
open_url "https://dashboard.stripe.com/sandboxes"
step "Click 'Create sandbox'."
step "Name it so it is obvious later, e.g. subscription-service."
step "Open it. The account picker, top left, should now show that name."
note "The old sandbox is untouched. This wizard deletes nothing in Stripe."
pause "Created it and switched into it?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Its API key"
say "Each sandbox has its own keys. Make sure the account picker still shows the"
say "new sandbox before copying, or you will paste the old one."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the Secret key row, click 'Reveal test key' and copy it (sk_test_...)."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"

if [[ "$STRIPE_SECRET_KEY" != sk_test_* ]]; then
  warn "That is not a sandbox key: it should start sk_test_. Nothing was written."
  exit 1
fi

say "Checking the key, and that this really is a fresh sandbox..."
PRODUCT_COUNT=$(STRIPE_API_KEY="$STRIPE_SECRET_KEY" "$PY" - <<'PY' || true
import os
import stripe
stripe.api_key = os.environ["STRIPE_API_KEY"]
try:
    print(len(stripe.Product.list(limit=20, active=True).data))
except Exception as exc:  # bad key, network, anything
    print(f"error:{type(exc).__name__}")
PY
)
case "$PRODUCT_COUNT" in
  error:*)
    warn "Stripe rejected that key ($PRODUCT_COUNT). Nothing was written."
    exit 1 ;;
  0)
    say "Key works, and the sandbox is empty." ;;
  *)
    warn "Key works, but this sandbox already has $PRODUCT_COUNT active product(s)."
    warn "That may mean the account picker was still on the old sandbox."
    confirm "Continue with this key anyway?" || exit 1 ;;
esac
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Products and prices"
say "Creating Plus and Pro, each with a monthly and an annual price, from"
say "app/plans.py. Every price is stamped with its tier, which is what lets a"
say "grandfathered price keep working after you change what you charge."
"$PY" -m scripts.seed_stripe || { warn "seeding failed; fix the error above and re-run"; exit 1; }
say ""
say "Reading the price ids back from Stripe by lookup key..."
while IFS= read -r line; do
  [[ "$line" == STRIPE_PRICE_* ]] || continue
  write_env "${line%%=*}" "${line#*=}"
done < <("$PY" - <<'PY'
import stripe
from app.config import get_settings
from app.plans import BillingInterval, Tier

settings = get_settings()
stripe.api_key = settings.stripe_secret_key
for tier in (Tier.PLUS, Tier.PRO):
    for interval in BillingInterval:
        found = stripe.Price.list(
            lookup_keys=[f"{tier.value}_{interval.value}"], active=True, limit=1
        ).data
        if found:
            print(f"STRIPE_PRICE_{tier.value.upper()}_{interval.value.upper()}={found[0].id}")
PY
)

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Customer portal"
say "The portal only offers the plans its configuration lists. Left unset, it"
say "shows the customer the plan they already have and no way to change it."
PORTAL_OUTPUT=$("$PY" -m scripts.configure_portal)
printf '%s\n' "$PORTAL_OUTPUT" | sed 's/^/  /'
PORTAL_ID=$(printf '%s' "$PORTAL_OUTPUT" | grep -oE 'bpc_[A-Za-z0-9]+' | tail -1 || true)
if [[ -n "$PORTAL_ID" ]]; then
  write_env STRIPE_PORTAL_CONFIGURATION_ID "$PORTAL_ID"
else
  warn "No bpc_ id in that output; set STRIPE_PORTAL_CONFIGURATION_ID by hand."
  SKIPPED+=("STRIPE_PORTAL_CONFIGURATION_ID")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Webhook signing secret"
say "Access is granted by the webhook, never by the browser's return from"
say "checkout, so local development needs the CLI forwarding this sandbox's"
say "events to the API."
WHSEC=$(stripe listen --print-secret --api-key "$STRIPE_SECRET_KEY" 2>/dev/null | tail -1 || true)
if [[ "$WHSEC" == whsec_* ]]; then
  write_env STRIPE_WEBHOOK_SECRET "$WHSEC"
else
  warn "Could not read a signing secret from the CLI."
  SKIPPED+=("STRIPE_WEBHOOK_SECRET (run: stripe listen --print-secret)")
fi
say ""
say "While developing, run this in a second terminal:"
note "  stripe listen --api-key \"\$(grep ^STRIPE_SECRET_KEY= .env | cut -d= -f2-)\" \\"
note "    --forward-to localhost:8000/v1/webhooks/stripe"
warn "A deployed environment needs its own endpoint secret from the Dashboard;"
warn "the CLI's secret is only for your machine."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions secrets"
say "CI runs the test-clock suite against this sandbox: nightly, and on pull"
say "requests that touch the service."
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
for key in STRIPE_PRICE_PLUS_MONTHLY STRIPE_PRICE_PLUS_ANNUAL \
           STRIPE_PRICE_PRO_MONTHLY STRIPE_PRICE_PRO_ANNUAL; do
  value=$(grep -E "^${key}=" "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
  if [[ -n "$value" ]]; then set_secret "$key" "$value"; else warn "no $key in .env"; fi
done
note "The webhook secret is deliberately not a CI secret: the suite calls the"
note "service's own code, never the HTTP endpoint."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Old rows in the dev database (optional)"
say "Your development database holds subscription rows whose Stripe customer"
say "ids live in the OLD sandbox. Nothing in the new one will ever match them."
warn "This includes the subscribers you created while testing: their customers"
warn "and subscriptions stay in the old sandbox, so the rows here are stale."
OLD_ROWS=$("$PY" - <<'PY' || true
import asyncio
import asyncpg
from dotenv import dotenv_values

async def main():
    dsn = dotenv_values(".env")["DATABASE_URL"].replace("postgresql+asyncpg", "postgresql")
    conn = await asyncpg.connect(dsn, statement_cache_size=0)
    print(await conn.fetchval("select count(*) from subscriptions where stripe_customer_id is not null"))
    await conn.close()

asyncio.run(main())
PY
)
say "Rows carrying a Stripe customer id: ${OLD_ROWS}"
note "Rows without a customer id are ordinary free accounts, never touched."
note "Declining is safe: stale rows simply never match, and the service now"
note "ignores subscriptions that are not on one of its own prices."
if [[ "${OLD_ROWS:-0}" != "0" ]] && confirm "Delete those ${OLD_ROWS} row(s)?"; then
  "$PY" - <<'PY'
import asyncio
import asyncpg
from dotenv import dotenv_values

async def main():
    dsn = dotenv_values(".env")["DATABASE_URL"].replace("postgresql+asyncpg", "postgresql")
    conn = await asyncpg.connect(dsn, statement_cache_size=0)
    before = await conn.fetchval("select count(*) from subscriptions")
    await conn.execute("delete from subscriptions where stripe_customer_id is not null")
    after = await conn.fetchval("select count(*) from subscriptions")
    print(f"  deleted {before - after} row(s); {after} left")
    await conn.close()

asyncio.run(main())
PY
else
  say "Left alone."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Prove it works"
say "The test-clock suite drives real Stripe objects through checkout, renewal,"
say "a failing card, the grace window, cancellation and an upgrade. About two"
say "minutes, against the new sandbox."
if confirm "Run it now?"; then
  "$REPO_ROOT/.venv/bin/pytest" integration/ -q || warn "Some cases failed; the output above says which."
else
  note "Run it later with: make testclock"
fi
say ""
warn "Restart anything already running so it reads the new .env:"
note "  - the API (make run)"
note "  - stripe listen, which must use the new key"
finish
